language: python
python:
  - "3.5"
before_install:
  - make install_deps
script:
  - make pep8
  - make test
deploy:
  provider: pypi
  user: khozzy
  password:
    secure: foo
  on:
    tags: true
    branch: master
